### ISSUE TITLE
Doesn't work with Babel transform-react-jsx enabled

### ISSUE THREAD

**Issue by jeron-diovis** [ArnaudBarre/vite-plugin-react-click-to-component#1]
I'm using jsx-control-statements in my project. To make them work in Vite setup, jsx has to be processed with `@babel/plugin-transform-react-jsx`, as it's discussed [here](https://github.com/vitejs/vite/discussions/7927#discussioncomment-4767333).

And strangely, enabling this transform completely disables this plugin – holding Option does nothing now.

Is it possible to make these two tools work together?

**Comment by ArnaudBarre** [comment]
Answered there: https://github.com/vitejs/vite/discussions/7927#discussioncomment-4937371

The issue is that you're not using the right transformation for development
