### ISSUE TITLE
WSL - `Could not open List.tsx in the editor.`

### ISSUE THREAD

**Issue by Pranay-Tej** [ArnaudBarre/vite-plugin-react-click-to-component#2]
- The package works in standalone Linux but not in WSL
- I'm on Windows 11, Ubuntu 20.04.6 LTS
- It'll be very helpful if we can make it work on WSL with some config

**Comment by ArnaudBarre** [comment]
Hello!

This plugin is using Vite internal launch editor feature. The upstream issue is: https://github.com/yyx990803/launch-editor/issues/16

A PR is welcome there if you find a way to make it work

**Comment by Pranay-Tej** [comment]
Thanks for pointing me to that issue.

The workaround I found is:

1. Add this to `.vscode/settings.json` 
2. Run the project from **VS Code's Terminal** instead of Windows' terminal

```json
.vscode/settings.json
{
  "terminal.integrated.env.linux": {
    "EDITOR": "code"
  }
}
```
