### ISSUE TITLE
This does not work when developing in a container. 

### ISSUE THREAD

**Issue by mayerlench** [ArnaudBarre/vite-plugin-react-click-to-component#7]
Im assuming the path its attempting to open in the container does not exist. Is there a workaround for this?

**Comment by ArnaudBarre** [comment]
See my comment here: https://github.com/ArnaudBarre/vite-plugin-react-click-to-component/pull/6#issuecomment-2482674073

This seems to be an issue, but it should be fixed at the Vite core level so for example opening files from the error overlay works
